<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <span class="head-title"><h1>¡Bienvenido al sistema de usuarios!</h1></span>
                <div id="status"></div>
            </div>
        </div>
    </div>
</div>
<script>
  function statusChangeCallback(response) {
    if (response.status === 'connected') {
      logged();
    } else if (response.status === 'not_authorized') {
      document.getElementById('status').innerHTML = 'Inicia sesión para que comiences a capturar los datos.';
    } else {
      $(".navbar-nav").children().first().show();
      document.getElementById('status').innerHTML = 'Inicia sesión para que comiences a capturar los datos.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '459158580910440',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.5' // use graph api version 2.5
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function logged() {
    FB.api('/me', function(response) {
        console.log(response);
      document.getElementById('status').innerHTML = 'Hola ' + response.name + '!';
      $(".navbar-nav").children().first().show();
    });
  }

  function getProfileImage() {
    FB.api("/me/picture?width=180&height=180",  function(response) {
    var profileImage = response.data.url.split('https://')[1], //remove https to avoid any cert issues
            randomNumber = Math.floor(Math.random()*256);
    console.log(profileImage);
    }); 
}

</script>