<div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-offset-2 col-md-4">
          <div class="form-group">
            <label for="nuevo_regsitro">Nuevo registro</label>
            <input type="nuevo_regsitro" class="form-control" id="nuevo_regsitro" placeholder="Ingresa un registro">
          </div>
        </div>
        <div class="col-md-1">
          <div class="form-group">
            <label for="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
            <button id="add" class="btn btn-primary" type="button">Guardar</button>
          </div>
          
        </div>
      </div>
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <table id="registros">
                  <thead>
                      <th>Registro</th>
                      <th>Fecha</th>
                  </thead>
                </table>
            </div>
        </div>
    </div>
</div>
